version: '3.9'

services:
  db:
    container_name: postgres-nodejs-learning
    image: 'postgres'
    restart: always
    ports:
      - '1234:5432'
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USER}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: