version: '3.9'

services:
  server:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - '2345:5432'
    environment:
      - POSTGRES_PASSWORD=qwerty76
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: