name: ESLINT
on: push
jobs:
  build:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npm run eslint
